import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { Provider } from "@/components/ui/provider";


import {
  ClerkProvider,
  SignIn,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
  <html lang="en" suppressHydrationWarning>
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      {/* SignedOut Layout */}
      <SignedOut>
        <div className="flex items-center justify-center mx-auto h-screen">
          <SignIn routing="hash" />
        </div>
      </SignedOut>

      {/* SignedIn Layout */}
      <SignedIn>
        <div className="min-h-screen flex flex-col">
          <Navbar bgColor="bg-yellow-300" />
          <Provider>{children}</Provider>
          <Footer />
        </div>
      </SignedIn>
    </body>
  </html>
</ClerkProvider>
  
  );
}
